// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
<<<<<<< HEAD
import { brokeredPreviewStorage } from './previewAuthStorage';
=======
>>>>>>> d4bc625e72d3a0b3bf650380eb1fa65146def7de

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
<<<<<<< HEAD
    storage: brokeredPreviewStorage(),
=======
    storage: localStorage,
>>>>>>> d4bc625e72d3a0b3bf650380eb1fa65146def7de
    persistSession: true,
    autoRefreshToken: true,
  }
});